### ISSUE TITLE
make data.gov accessible via https only

### ISSUE THREAD

**Issue by seyfro** [GSA/datagov-wptheme#587] opened 2015-02-19 13:12 UTC
data.gov is accessible via https only if users actively decide to use it. As TLS encryption not only secures sensitive data like user credentials but also ensures the authenticity and integrity of data transmitted and the sender (prevention of man-in-the-middle attacks as additional benefits amongst others) I wonder why data.gov hasnt yet made its website available via https only.

Nevertheless as ssllabs.com only assigns grade B (especially as RC4 cipher is still supported and forward secrecy not: https://www.ssllabs.com/ssltest/analyze.html?d=data.gov&s=172.230.231.192&latest) I would suggest to also follow the recommendations from the report. Technical guidelines which can help here can be found at https://bettercrypto.org

**Comment by philipashlock** [comment] 2015-02-25 22:59
Thanks @robertharm. I'm going to go ahead and close this as a duplicate of #352 but if you have any other comments to add, please add them there.

**Closed as completed by philipashlock** 2015-02-25 22:59 UTC
