### ISSUE TITLE
OPM duplicates and Collection search issues

### ISSUE THREAD

**Issue by bletalien** [GSA/datagov-wptheme#568] opened 2015-02-04 20:57 UTC
I found these duplications and verified that each appears only once in www.opm.gov/data.json:

Inspector General Audit Reports: http://catalog.data.gov/dataset/inspector-general-audit-reports and http://catalog.data.gov/dataset/inspector-general-audit-reports-22c18

Inspector General Semiannual Reports: http://catalog.data.gov/dataset/inspector-general-semiannual-reports and http://catalog.data.gov/dataset/inspector-general-semiannual-reports-cde32

Retirement Information Center Blog:
http://catalog.data.gov/dataset/retirement-information-center-blog and http://catalog.data.gov/dataset/retirement-information-center-blog-c2359

**Comment by rebeccawilliams** [comment] 2015-02-11 21:42
Thanks @bletalien! @konklone has noticed duplicates as well with Inspection General reports. I am renaming this issue to reflect that they are all in Catalog though.

Also, the Data.gov site search is perhaps picking up datasets in collections via group=site? See [here](https://www.data.gov/search-results/2/?q=inspector%20general&group=site).

@kvuppala, can you confirm on this? We might need to open a 2nd Issue.

**Comment by bletalien** [comment] 2015-02-11 21:49
@rebeccawilliams huh, interesting. It'd be good if just the parents showed up in that list. Also, I know I'm not helping with the errors here and there that are my fault (nothing that breaks our json, just the occasional child that isn't associated with its parent, that kind of thing). I didn't notice them until I started adding more to inventory.data.gov, so they'll have to stay the way they are in our data.json file until I can get the new entries through our approval process.

**Comment by kvuppala** [comment] 2015-02-12 23:05
@bletalien @rebeccawilliams looking at the duplicate, will plan to clean them up this week.

**Comment by kvuppala** [comment] 2015-02-13 22:55
@bletalien @rebeccawilliams Duplicates are resolved, for the Inspector General Audit Reports there were two duplicates which had to be deleted.  Strangely the  duplicates were created with in few  seconds in the initial harvest  source, we could reproduce this in any of the local instances.

@bletalien for the links that were deleted,   do we  need to set up a redirect of the URLs for example 
from http://catalog.data.gov/dataset/inspector-general-audit-reports-22c18 to http://catalog.data.gov/dataset/inspector-general-audit-reports.
site search will automatically will give the correct URL,  issue will be only for the ones that had this URL as book marked.

**Comment by bletalien** [comment] 2015-02-17 16:19
@kvuppala Thanks! If it's even the slightest bit of trouble, please don't bother with redirects. Otherwise, sure. It's really not a big deal one way or the other. Sorry for the delay in responding.

**Comment by rebeccawilliams** [comment] 2015-04-02 20:35
@kvuppala Looks like this is resolved now. Any reason to keep this open?

**Comment by kvuppala** [comment] 2015-04-06 21:49
@rebeccawilliams we can close the issue, we are taking care of adding the redirects with few other links we had in plan.  but redirects is something @bletalien mentioned not super critical.

**Closed as completed** 2015-04-10 15:18 UTC
Labels: duplicate, search
